### ISSUE TITLE
More problems with solve

### ISSUE THREAD

**Issue by ivanistheone** [sympy/sympy-live#105]
Running:
```
>>> solve(x-3,x)
```
produces results in an error `AttributeError: 'Not' object has no attribute 'canonical'`. The full stack trace is:
```
Traceback (most recent call last): File "<string>", line 1, in <module>
File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/solvers/solvers.py", line 889, in solve piece = Lambda(w, Piecewise((w, Ge(w, 0)), (-w, True)))
File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/functions/elementary/piecewise.py", line 110, in __new__ r = cls.eval(*newargs)
File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/functions/elementary/piecewise.py", line 128, in eval or1 = Or(*[cond for (_, cond) in args if cond != true])
File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/core/operations.py", line 410, in __new__ _args = frozenset(cls._new_args_filter(args))
File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/logic/boolalg.py", line 424, in _new_args_filter nc = (~c).canonical AttributeError: 'Not' object has no attribute 'canonical'
```

Was there some new version of SymPy pushed to app-engine? When is  46.393464279709602171 from?

**Comment by ivanistheone** [comment]
Can't reproduce today. Must have been a bad session in my browser or a temporary problem on app engine.
