### ISSUE TITLE
Error when run on documentation

### ISSUE THREAD

**Issue by ChristopherKing42** [sympy/sympy-live#119]
When running the first code block on http://docs.sympy.org/latest/modules/combinatorics/fp_groups.html, this error occurs:

```
>>> from sympy.combinatorics.free_groups import free_group, vfree_group, xfree_group
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named free_groups
>>> from sympy.combinatorics.fp_groups import FpGroup, CosetTable, coset_enumeration_r
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named fp_groups
```

**Comment by asmeurer** [comment]
SymPy Live has been updated to SymPy 1.2. This should work now.
