### ISSUE TITLE
LaTeX parser has antlr dependency

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy-live#131]
As LaTeX parser requires [antlr-python-runtime](https://docs.sympy.org/latest/modules/parsing.html#runtime-installation), the following code block from the docstring throws an error:
```
    >>> from sympy.parsing.latex import parse_latex  # doctest: +SKIP
    >>> expr = parse_latex(r"\frac {1 + \sqrt {\a}} {\b}")  # doctest: +SKIP
    >>> expr  # doctest: +SKIP
    (sqrt(a) + 1)/b
    >>> expr.evalf(4, subs=dict(a=5, b=2))  # doctest: +SKIP
    1.618
```
with the following traceback:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/sympy/sympy/parsing/latex/__init__.py", line 31, in parse_latex
    return _latex.parse_latex(s)
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/sympy/sympy/parsing/latex/_parse_latex_antlr.py", line 66, in parse_latex
    raise ImportError("LaTeX parsing requires the antlr4 python package,"
ImportError: LaTeX parsing requires the antlr4 python package, provided by pip (antlr4-python2-runtime or antlr4-python3-runtime) or conda (antlr-python-runtime)
```

**Comment by asmeurer** [comment]
Not likely we can do anything about this, at least with the current Live architecture.

**Comment by punish4424** [comment]
I found a solution for this.
Doing pip install antlr4-python3-runtime was not working for me, I was getting the same error.

Follow these steps :-

1. Install antlr4 from https://pypi.python.org/pypi/antlr4-python3-runtime (for python 3) or https://pypi.python.org/pypi/antlr4-python2-runtime ( for python 2). 

2. Extract the zip folder and inside the src folder you will find a folder named "antlr4". Copy that folder and paste that in your virtual-environment --> lib -- > python(2 or 3) --> site-packages.

3. Run your script again and it'll work fine.

**Comment by Fackor** [comment]
> I found a solution for this.
> Doing pip install antlr4-python3-runtime was not working for me, I was getting the same error.
> 
> Follow these steps :-
> 
>     1. Install antlr4 from https://pypi.python.org/pypi/antlr4-python3-runtime (for python 3) or https://pypi.python.org/pypi/antlr4-python2-runtime ( for python 2).
> 
>     2. Extract the zip folder and inside the src folder you will find a folder named "antlr4". Copy that folder and paste that in your virtual-environment --> lib -- > python(2 or 3) --> site-packages.
> 
>     3. Run your script again and it'll work fine.

Can you please guide me a little on how to get this set up in a local machine. I don't quite understand which zip folder you are referring to in the second point.

Also, is there any way to do this using a conda installer.

**Comment by csdrli** [comment]
Install an earlier version

pip install antlr4-python3-runtime==4.x.x

**Comment by fcrozatier** [comment]
As of 02/2023 you need antlr 4.10 to run `parse_latex`.
See my answer [here](https://stackoverflow.com/questions/63922403/latex-to-sympy-conversion/75314594#75314594)

**Comment by Mhieu14** [comment]
This is work for me:
`pip install antlr4-python3-runtime==4.11`

**Comment by Yahuicai** [comment]
> This is work for me: `pip install antlr4-python3-runtime==4.11`

yes!

**Comment by asmeurer** [comment]
The source for live is now at https://github.com/sympy/live. I don't know where the dependencies are listed but it should be possible to just add this.

**Comment by ivanistheone** [comment]
I tried running  `!pip install antlr4-python3-runtime` in jupyter lite, and it fails.

<img width="1035" alt="Image" src="https://github.com/user-attachments/assets/39854c79-ace9-4613-b200-a471f25af524" />

I think it's literally trying to install a binary on the system host, which won't work for us since we're running in a Pyodide environment. 

Motion to close as can't fix.

**Comment by agriyakhetarpal** [comment]
Hi @ivanistheone, you were using `!pip install` above, but you instead need to use the magic to avoid calling `pip` and call `piplite` instead, using `%pip install antlr4-python3-runtime` :) See below:

<img width="1512" alt="A screenshot of a Jupyter notebook showing Python code and error messages. The code attempts to install and use the antlr4-python3-runtime package. The first cell shows an OSError when trying to use pip install, followed by a successful import of antlr4 and creation of an InputStream with 'hello world' that returns size 11." src="https://github.com/user-attachments/assets/0fd26e93-c4e2-4520-b2e4-0dbc2f2e9298" />

I think this can be closed, though, as "completed" because ANTLR is working as intended in Pyodide.

**Comment by ivanistheone** [comment]
I can confirm `%pip` succeeds in installing `antlr4-python3-runtime` and then the `parse_latex` call works.

Note I **you to specify the exact version 4.11.1** as follows `%pip install antlr4-python3-runtime==4.11.1`:
```
%pip install antlr4-python3-runtime==4.11.1
from sympy.parsing.latex import parse_latex
expr = parse_latex(r"\frac {1 + \sqrt {\a}} {\b}") 
expr
```
Live evaluate link [here](https://live.sympy.org/?evaluate=%25pip%20install%20antlr4-python3-runtime%3D%3D4.11.1%0Afrom%20sympy.parsing.latex%20import%20parse_latex%0Aexpr%20%3D%20parse_latex(r%22%5Cfrac%20%7B1%20%2B%20%5Csqrt%20%7B%5Ca%7D%7D%20%7B%5Cb%7D%22)%20%0Aexpr%0A).

On the other hand, this fails:
```
%pip install antlr4-python3-runtime
from sympy.parsing.latex import parse_latex
expr = parse_latex(r"\frac {1 + \sqrt {\a}} {\b}") 
expr
```
Evaluate link [here](https://live.sympy.org/?evaluate=%25pip%20install%20antlr4-python3-runtime%0Afrom%20sympy.parsing.latex%20import%20parse_latex%0Aexpr%20%3D%20parse_latex(r%22%5Cfrac%20%7B1%20%2B%20%5Csqrt%20%7B%5Ca%7D%7D%20%7B%5Cb%7D%22)%20%0Aexpr%0A).

Because the `%pip install` commands installs the latest `antlr4-python3-runtime==4.13.2` but the SymPy code is [looking specifically for version 4.11](https://github.com/sympy/sympy/blob/master/sympy/parsing/latex/_parse_latex_antlr.py#L65) for some reason.


Closing this issue since the `%pip install antlr4-python3-runtime==4.11.1` command works. 

Still might be good to followup to know why SymPy parsing wants 4.11.* and rejects newer versions...

**Comment by agriyakhetarpal** [comment]
🤔 Looking at some git blame results from way back, there have been changes like this one: https://github.com/sympy/sympy/commit/39a9e55f83ac6e4fe47965189219e7971b4cad86 that rely on functionality that easily breaks between versions. https://github.com/sympy/sympy/pull/24097#issuecomment-1262974982 mentions that ANTLR is fragile in the sense that it doesn't offer minor version compatibility. I don't know if that has changed a couple of years down the line...
