### ISSUE TITLE
SymPy Live giving errors

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-live#137]
Whenever you evaluate something it says `Error: .`. Here is an example traceback from the logs

```pytb
(/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:291)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 273, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7cb976f64e72c78c/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/shell.py", line 771, in post
    live.evaluate(PREEXEC, session)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/shell.py", line 453, in evaluate
    if name not in old_globals or val != old_globals[name]:
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/core/basic.py", line 352, in __ne__
    return not self == other
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/sets/fancysets.py", line 1110, in __eq__
    return other == ComplexRegion(S.Reals*S.Reals)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/sets/fancysets.py", line 856, in __new__
    obj = ImageSet.__new__(cls, Lambda((x, y), x + I*y), sets)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/core/expr.py", line 151, in __mul__
    return Mul(self, other)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/core/compatibility.py", line 908, in wrapper
    del cache[oldkey]
KeyError: [<class 'sympy.core.mul.Mul'>, I, _y, <class 'sympy.core.assumptions.ManagedProperties'>, <class 'sympy.core.numbers.ImaginaryUnit'>, <class 'sympy.core.symbol.Dummy'>]
```

**Comment by oscarbenjamin** [comment]
I think it's fixed now

**Comment by oscarbenjamin** [comment]
I updated SymPy Live to 1.5 and it all seems to be working. The instructions for deploying need to be updated though...
