### ISSUE TITLE
Sympy live shell is giving UnicodeEncodeError

### ISSUE THREAD

**Issue by guu1227** [sympy/sympy-live#197]
This is occurring for me every time I try to run anything in sympy live, looks like a case of needing to use `.encode` for encoding unicode:
`>>> str(Integral(sqrt(1/x), x))
Exception in SymPy Live of type 
<type 'exceptions.UnicodeEncodeError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/handlers.py", line 271, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/shell.py", line 280, in evaluate
    exec code in statement_module.__dict__
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/printing/pretty/pretty.py", line 2665, in pretty_print
    imaginary_unit=imaginary_unit))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3f4b27f16594164f/python27/python27_lib/versions/1/google/appengine/runtime/request_environment.py", line 104, in write
    self._request.errors.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2320' in position 0: ordinal not in range(128)`

**Comment by ivanistheone** [comment]
Traceback reformatted for readability:

```
>>> str(Integral(sqrt(1/x), x))
Exception in SymPy Live of type <type 'exceptions.UnicodeEncodeError'>
File "app/handlers.py", line 271, in post live.evaluate(statement, session, printer, stream)
File "app/shell.py", line 280, in evaluate exec code in statement_module.__dict__ File "<string>", line 1, in <module>
File "pretty.py", line 2665, in pretty_print imaginary_unit=imaginary_unit))
File "google/appengine/runtime/request_environment.py", line 104, in write self._request.errors.write(data) UnicodeEncodeError: 'ascii' codec can't encode character u'\u2320' ('TOP HALF INTEGRAL') in position 0: ordinal not in range(128)
```

______


I'm not able to reproduce. I tried with  both LaTeX and Unicode Output Formats:

<img width="353" alt="Screen Shot 2021-10-30 at 8 11 10 AM" src="https://user-images.githubusercontent.com/163966/139532412-da4a102d-85cf-45c5-b9bc-9aa0b8fc685d.png">

Possibly something earlier the session broke, but `Integral(sqrt(1/x), x)` in isolation seems to work:

@guu1227 could you please try opening this link in an incognito/private browser to test:
https://live.sympy.org/?evaluate=Integral(sqrt(1%2Fx)%2C%20x)%0A%23--%0Astr(Integral(sqrt(1%2Fx)%2C%20x))%0A%23--%0A

**Comment by guu1227** [comment]
Sorry I missed this comment 
I'm not getting the trace with either a private browser or a normal browser on the linked page. It only seems to be occurring when I try to use the pop up live shell on the sympy tutorial web page. 
Also, it doesn't happen when I open the tutorial page in a private browser. The trace does appear if I try to run any command on the tutorial page's sympy live shell using a normal browser, though.
