### ISSUE TITLE
jQuery Error executing docs examples in live shell

### ISSUE THREAD

**Issue by ivanistheone** [sympy/sympy-live#199]
Clicking on the second example in https://docs.sympy.org/latest/tutorial/calculus.html
`>>> diff(cos(x), x)`
opens the live shell sidebar with a  spining indicator running, and never return the answer due to:

```
live-core.js:943 Uncaught TypeError: Cannot read properties of undefined (reading 'Queue')
    at g.done (live-core.js:943:29)
    at g.done (live-sphinx.js:146:14)
    at g.done (classy.js:8:507)
    at g.<anonymous> (live-core.js:904:26)
    at Object.i [as success] (jquery.js:2:88736)
    at c (jquery.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery.js:2:29039)
    at l (jquery.js:2:79800)
    at XMLHttpRequest.<anonymous> (jquery.js:2:82254)
```

<img width="530" alt="Screen Shot 2022-04-08 at 2 02 43 PM" src="https://user-images.githubusercontent.com/163966/162497600-9f7ac951-8598-4429-94ab-537fd8c890ab.png">

Looking in the network tab I see the POST to evaluate succeeded and returned the correct ans:
<img width="1269" alt="Screen Shot 2022-04-08 at 2 06 39 PM" src="https://user-images.githubusercontent.com/163966/162497584-5ee3bd56-c89b-4555-9d62-8ccd695da2f4.png">

so the live-shell backend is working.

it must be some frontend thing on the docs page

**Comment by asmeurer** [comment]
Looks like the Live extension is broken in the docs. The main Live site still works. Maybe the jquery that Sphinx uses is not compatible with the version expected by Live?

**Comment by asmeurer** [comment]
Note that the dev version of the docs has removed the Live extension, and this will also be the case in the next release. However, if we can easily hotfix the current "latest" version to fix this, we should.
