### ISSUE TITLE
Cannot import autowrap on sympy live

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy-live#82]
```
>>> from sympy.utilities.autowrap import autowrap
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/utilities/autowrap.py", line 76, in <module>
    from subprocess import STDOUT, CalledProcessError
ImportError: cannot import name STDOUT
```

**Comment by tokencolour** [comment]
Can something be done about it? Apparently the app engine doesn't have any compilers installed.

**Comment by asmeurer** [comment]
No. I don't think it will be possible.
